let titulo=document.querySelector("#nombreProducto");
titulo.style.color="blue";
titulo.style.fontSize="70px";
let precio=document.getElementById("precioProducto");
precio.innerText="$450"
precio.style.fontSize="35px";
precio.style.color="lightgreen";
precio.style.fontWeight="bold";
precio.style.textDecoration="underline";
titulo.style.backgroundColor="black";
titulo.style.textAlign="center";